version: "3"
services:
  jenkins:
    build:
      context: ${CUSTOM_IMAGE_FOLDER}
    privileged: true
    user: root
    ports:
      - ${HOST_PORT_WEB}:8080
      - ${HOST_PORT_API}:50000
    volumes:
      - ${HOST_JENKINS_DATA}:/var/jenkins_home
      - ${HOST_DOCKER}:/var/run/docker.sock

